# Vaibhav Sharma 1803210169 CSE 2nd year

## Importing the packages

In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

## Loading the data

In [6]:
# this dataset contains age-group wise data
agrp = pd.read_csv("../DataSet/AgeGroupDetails.csv")
agrp

   Sno AgeGroup  TotalCases Percentage
0    1      0-9          22      3.18%
1    2    10-19          27      3.90%
2    3    20-29         172     24.86%
3    4    30-39         146     21.10%
4    5    40-49         112     16.18%
5    6    50-59          77     11.13%
6    7    60-69          89     12.86%
7    8    70-79          28      4.05%
8    9     >=80          10      1.45%
9   10  Missing           9      1.30%

In [7]:
# zone wise data of the states
zone = pd.read_csv("../DataSet/zone-wise-data.csv")
zone.head(10)

,district,districtcode,lastupdated,source,state,statecode,zone
0,Nicobars,AN_Nicobars,01/05/2020,https://www.facebook.com/airnewsalerts/photos/...,Andaman and Nicobar Islands,AN,Green
1,North and Middle Andaman,AN_North and Middle Andaman,01/05/2020,https://www.facebook.com/airnewsalerts/photos/...,Andaman and Nicobar Islands,AN,Green
2,South Andaman,AN_South Andaman,01/05/2020,https://www.facebook.com/airnewsalerts/photos/...,Andaman and Nicobar Islands,AN,Red
3,Anantapur,AP_Anantapur,01/05/2020,https://www.facebook.com/airnewsalerts/photos/...,Andhra Pradesh,AP,Orange
4,Chittoor,AP_Chittoor,01/05/2020,https://www.facebook.com/airnewsalerts/photos/...,Andhra Pradesh,AP,Red
5,East Godavari,AP_East Godavari,01/05/2020,https://www.facebook.com/airnewsalerts/photos/...,Andhra Pradesh,AP,Orange
6,Guntur,AP_Guntur,01/05/2020,https://www.facebook.com/airnewsalerts/photos/...,Andhra Pradesh,AP,Red
7,Krishna,AP_Krishna,01/05/2020,https://www.facebook.com/airnewsalerts/photos/...,Andhra Pradesh,AP,Red
8,Kurnool,AP_Kurnool,01/05/2020,https://www.facebook.com/airnewsalerts/photos/...,Andhra Pradesh,AP,Red
9,Prakasam,AP_Prakasam,01/05/2020,https://www.facebook.com/airnewsalerts/photos/...,Andhra Pradesh,AP,Orange

In [8]:
country = pd.read_csv("../DataSet/covid_19_Country-wise-data.csv")
country.head(10)

,SNo,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,1,01/22/2020,Anhui,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
1,2,01/22/2020,Beijing,Mainland China,1/22/2020 17:00,14.0,0.0,0.0
2,3,01/22/2020,Chongqing,Mainland China,1/22/2020 17:00,6.0,0.0,0.0
3,4,01/22/2020,Fujian,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
4,5,01/22/2020,Gansu,Mainland China,1/22/2020 17:00,0.0,0.0,0.0
5,6,01/22/2020,Guangdong,Mainland China,1/22/2020 17:00,26.0,0.0,0.0
6,7,01/22/2020,Guangxi,Mainland China,1/22/2020 17:00,2.0,0.0,0.0
7,8,01/22/2020,Guizhou,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
8,9,01/22/2020,Hainan,Mainland China,1/22/2020 17:00,4.0,0.0,0.0
9,10,01/22/2020,Hebei,Mainland China,1/22/2020 17:00,1.0,0.0,0.0

In [9]:
beds = pd.read_csv("../DataSet/HospitalBedsIndia.csv")
beds.head(10)

,Sno,State/UT,NumPrimaryHealthCenters_HMIS,NumCommunityHealthCenters_HMIS,NumSubDistrictHospitals_HMIS,NumDistrictHospitals_HMIS,TotalPublicHealthFacilities_HMIS,NumPublicBeds_HMIS,NumRuralHospitals_NHP18,NumRuralBeds_NHP18,NumUrbanHospitals_NHP18,NumUrbanBeds_NHP18
0,1,Andaman & Nicobar Islands,27,4,NaN,3,34,1246,27,575,3,500
1,2,Andhra Pradesh,1417,198,31.0,20,1666,60799,193,6480,65,16658
2,3,Arunachal Pradesh,122,62,NaN,15,199,2320,208,2136,10,268
3,4,Assam,1007,166,14.0,33,1220,19115,1176,10944,50,6198
4,5,Bihar,2007,63,33.0,43,2146,17796,930,6083,103,5936
5,6,Chandigarh,40,2,1.0,4,47,3756,0,0,4,778
6,7,Chhattisgarh,813,166,12.0,32,1023,14354,169,5070,45,4342
7,8,Dadra & Nagar Haveli,9,2,1.0,1,13,568,10,273,1,316
8,9,Daman & Diu,4,2,NaN,2,8,298,5,240,0,0
9,10,Delhi,534,25,9.0,47,615,20572,0,0,109,24383

### Loading live Data from API

In [10]:
import http.client
import mimetypes
conn = http.client.HTTPSConnection("api.covid19api.com")
conn.request("GET", "/total/country/india", '', {})
res = conn.getresponse()
api_data = res.read()
print(api_data.decode("utf-8"))

[{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":0,"Deaths":0,"Recovered":0,"Active":0,"Date":"2020-01-22T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":0,"Deaths":0,"Recovered":0,"Active":0,"Date":"2020-01-23T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":0,"Deaths":0,"Recovered":0,"Active":0,"Date":"2020-01-24T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":0,"Deaths":0,"Recovered":0,"Active":0,"Date":"2020-01-25T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":0,"Deaths":0,"Recovered":0,"Active":0,"Date":"2020-01-26T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":0,"Deaths":0,"Recovered":0,"Active":0,"Date":"2020-01-27T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":0,"Deaths":0,"Recovered":0,"Active":0,"Date":"2020-01-28T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":0,"Deaths":0,"Recovered":0,"Active":0,"Date":"2020-01-29T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":1,"Deaths":0,"Recovered":0,"Active":1,"Date":"2020-01-30T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":1,"Deaths":0,"Recovered":0,"Active":1,"Date":"2020-01-31T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":1,"Deaths":0,"Recovered":0,"Active":1,"Date":"2020-02-01T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":2,"Deaths":0,"Recovered":0,"Active":2,"Date":"2020-02-02T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":3,"Deaths":0,"Recovered":0,"Active":3,"Date":"2020-02-03T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":3,"Deaths":0,"Recovered":0,"Active":3,"Date":"2020-02-04T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":3,"Deaths":0,"Recovered":0,"Active":3,"Date":"2020-02-05T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":3,"Deaths":0,"Recovered":0,"Active":3,"Date":"2020-02-06T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":3,"Deaths":0,"Recovered":0,"Active":3,"Date":"2020-02-07T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":3,"Deaths":0,"Recovered":0,"Active":3,"Date":"2020-02-08T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":3,"Deaths":0,"Recovered":0,"Active":3,"Date":"2020-02-09T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":3,"Deaths":0,"Recovered":0,"Active":3,"Date":"2020-02-10T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":3,"Deaths":0,"Recovered":0,"Active":3,"Date":"2020-02-11T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":3,"Deaths":0,"Recovered":0,"Active":3,"Date":"2020-02-12T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":3,"Deaths":0,"Recovered":0,"Active":3,"Date":"2020-02-13T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":3,"Deaths":0,"Recovered":0,"Active":3,"Date":"2020-02-14T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":3,"Deaths":0,"Recovered":0,"Active":3,"Date":"2020-02-15T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":3,"Deaths":0,"Recovered":3,"Active":0,"Date":"2020-02-16T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":3,"Deaths":0,"Recovered":3,"Active":0,"Date":"2020-02-17T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":3,"Deaths":0,"Recovered":3,"Active":0,"Date":"2020-02-18T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":3,"Deaths":0,"Recovered":3,"Active":0,"Date":"2020-02-19T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":3,"Deaths":0,"Recovered":3,"Active":0,"Date":"2020-02-20T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":3,"Deaths":0,"Recovered":3,"Active":0,"Date":"2020-02-21T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":3,"Deaths":0,"Recovered":3,"Active":0,"Date":"2020-02-22T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":3,"Deaths":0,"Recovered":3,"Active":0,"Date":"2020-02-23T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":3,"Deaths":0,"Recovered":3,"Active":0,"Date":"2020-02-24T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":3,"Deaths":0,"Recovered":3,"Active":0,"Date":"2020-02-25T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":3,"Deaths":0,"Recovered":3,"Active":0,"Date":"2020-02-26T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":3,"Deaths":0,"Recovered":3,"Active":0,"Date":"2020-02-27T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":3,"Deaths":0,"Recovered":3,"Active":0,"Date":"2020-02-28T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":3,"Deaths":0,"Recovered":3,"Active":0,"Date":"2020-02-29T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":3,"Deaths":0,"Recovered":3,"Active":0,"Date":"2020-03-01T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":5,"Deaths":0,"Recovered":3,"Active":2,"Date":"2020-03-02T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":5,"Deaths":0,"Recovered":3,"Active":2,"Date":"2020-03-03T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":28,"Deaths":0,"Recovered":3,"Active":25,"Date":"2020-03-04T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":30,"Deaths":0,"Recovered":3,"Active":27,"Date":"2020-03-05T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":31,"Deaths":0,"Recovered":3,"Active":28,"Date":"2020-03-06T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":34,"Deaths":0,"Recovered":3,"Active":31,"Date":"2020-03-07T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":39,"Deaths":0,"Recovered":3,"Active":36,"Date":"2020-03-08T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":43,"Deaths":0,"Recovered":3,"Active":40,"Date":"2020-03-09T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":56,"Deaths":0,"Recovered":4,"Active":52,"Date":"2020-03-10T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":62,"Deaths":1,"Recovered":4,"Active":57,"Date":"2020-03-11T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":73,"Deaths":1,"Recovered":4,"Active":68,"Date":"2020-03-12T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":82,"Deaths":2,"Recovered":4,"Active":76,"Date":"2020-03-13T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":102,"Deaths":2,"Recovered":4,"Active":96,"Date":"2020-03-14T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":113,"Deaths":2,"Recovered":13,"Active":98,"Date":"2020-03-15T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":119,"Deaths":2,"Recovered":13,"Active":104,"Date":"2020-03-16T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":142,"Deaths":3,"Recovered":14,"Active":125,"Date":"2020-03-17T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":156,"Deaths":3,"Recovered":14,"Active":139,"Date":"2020-03-18T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":194,"Deaths":4,"Recovered":15,"Active":175,"Date":"2020-03-19T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":244,"Deaths":5,"Recovered":20,"Active":219,"Date":"2020-03-20T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":330,"Deaths":4,"Recovered":23,"Active":303,"Date":"2020-03-21T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":396,"Deaths":7,"Recovered":27,"Active":362,"Date":"2020-03-22T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":499,"Deaths":10,"Recovered":27,"Active":462,"Date":"2020-03-23T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":536,"Deaths":10,"Recovered":40,"Active":486,"Date":"2020-03-24T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":657,"Deaths":12,"Recovered":43,"Active":602,"Date":"2020-03-25T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":727,"Deaths":20,"Recovered":45,"Active":662,"Date":"2020-03-26T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":887,"Deaths":20,"Recovered":73,"Active":794,"Date":"2020-03-27T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":987,"Deaths":24,"Recovered":84,"Active":879,"Date":"2020-03-28T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":1024,"Deaths":27,"Recovered":95,"Active":902,"Date":"2020-03-29T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":1251,"Deaths":32,"Recovered":102,"Active":1117,"Date":"2020-03-30T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":1397,"Deaths":35,"Recovered":123,"Active":1239,"Date":"2020-03-31T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":1998,"Deaths":58,"Recovered":148,"Active":1792,"Date":"2020-04-01T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":2543,"Deaths":72,"Recovered":191,"Active":2280,"Date":"2020-04-02T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":2567,"Deaths":72,"Recovered":192,"Active":2303,"Date":"2020-04-03T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":3082,"Deaths":86,"Recovered":229,"Active":2767,"Date":"2020-04-04T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":3588,"Deaths":99,"Recovered":229,"Active":3260,"Date":"2020-04-05T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":4778,"Deaths":136,"Recovered":375,"Active":4267,"Date":"2020-04-06T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":5311,"Deaths":150,"Recovered":421,"Active":4740,"Date":"2020-04-07T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":5916,"Deaths":178,"Recovered":506,"Active":5232,"Date":"2020-04-08T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":6725,"Deaths":226,"Recovered":620,"Active":5879,"Date":"2020-04-09T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":7598,"Deaths":246,"Recovered":774,"Active":6578,"Date":"2020-04-10T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":8446,"Deaths":288,"Recovered":969,"Active":7189,"Date":"2020-04-11T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":9205,"Deaths":331,"Recovered":1080,"Active":7794,"Date":"2020-04-12T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":10453,"Deaths":358,"Recovered":1181,"Active":8914,"Date":"2020-04-13T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":11487,"Deaths":393,"Recovered":1359,"Active":9735,"Date":"2020-04-14T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":12322,"Deaths":405,"Recovered":1432,"Active":10485,"Date":"2020-04-15T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":13430,"Deaths":448,"Recovered":1768,"Active":11214,"Date":"2020-04-16T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":14352,"Deaths":486,"Recovered":2041,"Active":11825,"Date":"2020-04-17T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":15722,"Deaths":521,"Recovered":2463,"Active":12738,"Date":"2020-04-18T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":17615,"Deaths":559,"Recovered":2854,"Active":14202,"Date":"2020-04-19T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":18539,"Deaths":592,"Recovered":3273,"Active":14674,"Date":"2020-04-20T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":20080,"Deaths":645,"Recovered":3975,"Active":15460,"Date":"2020-04-21T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":21370,"Deaths":681,"Recovered":4370,"Active":16319,"Date":"2020-04-22T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":23077,"Deaths":721,"Recovered":5012,"Active":17344,"Date":"2020-04-23T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":24530,"Deaths":780,"Recovered":5498,"Active":18252,"Date":"2020-04-24T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":26283,"Deaths":825,"Recovered":5939,"Active":19519,"Date":"2020-04-25T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":27890,"Deaths":881,"Recovered":6523,"Active":20486,"Date":"2020-04-26T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":29451,"Deaths":939,"Recovered":7137,"Active":21375,"Date":"2020-04-27T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":31324,"Deaths":1008,"Recovered":7747,"Active":22569,"Date":"2020-04-28T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":33062,"Deaths":1079,"Recovered":8437,"Active":23546,"Date":"2020-04-29T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":34863,"Deaths":1154,"Recovered":9068,"Active":24641,"Date":"2020-04-30T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":37257,"Deaths":1223,"Recovered":10007,"Active":26027,"Date":"2020-05-01T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":39699,"Deaths":1323,"Recovered":10819,"Active":27557,"Date":"2020-05-02T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":42505,"Deaths":1391,"Recovered":11775,"Active":29339,"Date":"2020-05-03T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":46437,"Deaths":1566,"Recovered":12847,"Active":32024,"Date":"2020-05-04T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":49400,"Deaths":1693,"Recovered":14142,"Active":33565,"Date":"2020-05-05T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":52987,"Deaths":1785,"Recovered":15331,"Active":35871,"Date":"2020-05-06T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":56351,"Deaths":1889,"Recovered":16776,"Active":37686,"Date":"2020-05-07T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":59695,"Deaths":1985,"Recovered":17887,"Active":39823,"Date":"2020-05-08T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":62808,"Deaths":2101,"Recovered":19301,"Active":41406,"Date":"2020-05-09T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":67161,"Deaths":2212,"Recovered":20969,"Active":43980,"Date":"2020-05-10T00:00:00Z"},{"Country":"India","CountryCode":"","Province":"","City":"","CityCode":"","Lat":"0","Lon":"0","Confirmed":70768,"Deaths":2294

In [11]:
api = pd.read_json(api_data)
api.tail(5)

,Active,City,CityCode,Confirmed,Country,CountryCode,Date,Deaths,Lat,Lon,Province,Recovered
136,120981,,,246622,India,,2020-06-06,6946,0,0,,118695
137,126431,,,257486,India,,2020-06-07,7207,0,0,,123848
138,129360,,,265928,India,,2020-06-08,7473,0,0,,129095
139,133726,,,276146,India,,2020-06-09,7750,0,0,,134670
140,133632,,,276583,India,,2020-06-10,7745,0,0,,135206